### ISSUE TITLE
Поломался запуск в CI CD

### ISSUE THREAD

**Issue by Sozonov2** [VKCOM/vk-miniapps-deploy#57]
Сейчас при запуске деплоя в CICD, с полем "noprompt": true все равно получаем запрос "Would you like to update prod urls?". Ожидание ответа ломает сборку в CICD.

**Comment by svyatoslavpavlov** [comment]
Все еще есть проблема

**Comment by svyatoslavpavlov** [comment]
да, конечно

```
image: node:18.20

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - mini-app/node_modules/

build:
  stage: build
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - cd mini-app
    - cp .env.example .env
    - pnpm run build
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - cd mini-app
    - cp .env.example .env
    - pnpm run build
    - env MINI_APPS_ACCESS_TOKEN=$DEPLOY_TOKEN pnpm run deploy
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

```

```json
{
  "static_path": "build",
  "app_id": "6819359",
  "endpoints": {
    "mobile": "index.html",
    "mvk": "index.html",
    "web": "index.html"
  },
  "noprompt": true
}
```

Все работало хорошо до какого-то момента

Запуск на CI (локально та же проблема, запуская на macos)
